; PlatformIO project for a3-motion firmware

[env:esp32-s3-devkitc-1-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8
board_dir = boards
framework = arduino

monitor_speed = 115200
monitor_port = /dev/ttyACM1
upload_port = /dev/ttyACM1

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  adafruit/Adafruit NeoPixel
  thomasfredericks/Bounce2
